name: Lint

on: 
    pull_request:
        types: [opened, edited, reopened]
    push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: TrueBrain/actions-flake8@v2
        with:
          flake8_version: 6.0.0
          path: asf_search
          max_line_length: 100
