name: tests

on: [pull_request, push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Temp disabled until pytest is ready:
      - name: Install Dependancies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .
          python3 -m pip install pytest requests-mock coverage pytest-cov pytest-automation

      - name: Run Tests
        run: python3 -m pytest --cov=asf_search --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: asf_admin pytest
          verbose: true
