name: tests

on: [pull_request, push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Get the code:
      - uses: actions/checkout@v2
      ## Removing until test suite is added:
      # - name: Run the test suite
      #   run: |
      #    python3 -m pip install .
      #    pytest -n auto .
